=== RebecaMadi/projeto-buscador/coletas-api/coletasAPI/coletasapi/helpers/object_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
  "tribunal": {
      "type": "string",
      "enum": ["TJCE", "TJAL"]
  },
  "classe": {
      "type": ["string", "null"]
  },
  "area": {
      "type": ["string", "null"]
  },
  "assunto": {
      "type": ["string", "null"]
  },
  "data_de_distribuicao": {
      "type": ["string", "null"],
      "format": "date"
  },
  "juiz": {
      "type": ["string", "null"]
  },
  "valor_da_acao": {
      "type": ["number", "null"]
  },
  "segredo_justica": {
      "type": "boolean"
  },
  "existe": {
      "type": "boolean"
  },
  "partes_do_processo": {
      "type": "array",
      "items": {
      "type": "object",
      "properties": {
          "nome": {
          "type": "string"
          },
          "papel": {
          "type": "string"
          },
          "advogado(as)": {
          "type": ["array", "null"],
          "items": {
              "type": "string"
          }
          }
      },
      "required": ["nome", "papel"]
      }
  },
  "lista_das_movimentacoes": {
      "type": "array",
      "items": {
      "type": "object",
      "properties": {
          "data": {
          "type": "string",
          "format": "date"
          },
          "movimento": {
          "type": "string"
          }
      },
      "required": ["data", "movimento"]
      }
  },
  "instancia": {
      "type": "integer",
      "enum": [1, 2]
  },
  "numero_do_processo": {
      "type": ["string", "null"]
  }
  },
  "required": [
  "tribunal",
  "classe",
  "area",
  "assunto",
  "data_de_distribuicao",
  "juiz",
  "valor_da_acao",
  "partes_do_processo",
  "lista_das_movimentacoes",
  "instancia",
  "numero_do_processo"
  ]
}

=== RebecaMadi/projeto-buscador/kb-kafka-pipeline/parser/tests/integration-tests/test_message.json
{
    "tribunal": "TJCE",
    "classe": "Ação Ordinária",
    "area": "Cível",
    "assunto": "Exploração do trabalho infantil",
    "data_de_distribuicao": "2023-05-10",
    "juiz": "Dr. João Silva",
    "valor_da_acao": 50000.75,
    "segredo_justica": false,
    "instancia": 1,
    "numero_do_processo": "1234567-89.2023.8.09.0001",
    "partes_do_processo": [
        {
            "nome": "Maria Souza",
            "papel": "Autor",
            "advogado(as)": ["Dr. Carlos Almeida"]
        },
        {
            "nome": "Empresa XYZ Ltda.",
            "papel": "Réu",
            "advogado(as)": ["Dra. Ana Pereira"]
        }
    ],
    "lista_das_movimentacoes": [
        {"data": "2023-05-11", "movimento": "Distribuído por sorteio"},
        {"data": "2023-05-15", "movimento": "Citação expedida"}
    ]
}
